[project]
name = "robotics"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "spidev",
    "brickpi3 @ git+https://github.com/DexterInd/BrickPi3.git#subdirectory=Software/Python",
]

[dependency-groups]
dev = []

[tool.uv.sources]
spidev = { path = "vendor/spidev_shim", marker = "sys_platform == 'darwin'" }

###
# type-checker configuration
###
[tool.basedpyright]
pythonVersion = "3.13"
typeCheckingMode = "strict"
failOnWarnings = false
reportAny = "warning"
reportUnknownMemberType = "information"
reportUnknownArgumentType = "information"
reportUnknownVariableType = "warning"
reportUnknownParameterType = "warning"
reportMissingParameterType = "warning"
reportMissingTypeStubs = "information"
reportInvalidCast = "warning"
reportUnnecessaryCast = "warning"
reportUnnecessaryTypeIgnoreComment = "warning"

exclude = [
    "**/.venv",
    "**/venv",
    "**/__pycache__",
    "**/exo_scripts",
    "**/.direnv",
    "**/rust",
]
stubPath = "typings"

[[tool.basedpyright.executionEnvironments]]
root = "src/robotics"

[[tool.basedpyright.executionEnvironments]]
root = "."

###
# ruff configuration
###
[tool.ruff.lint]
extend-select = ["I", "N", "B", "A", "PIE", "SIM"]
